version: "2"

services:
  dev:
    image: 415148673/ruby-node-base-image@sha256:411a2e26da1e97f3d01e965b5511378aa9c2163c70d3b44d1ae24544c668ba9f
    environment:
      - RACK_ENV=production
      - YUNBI_API_ENDPOINT=https://yunbi.com/api/v2
      - BITTREX_API_ENDPOINT=https://bittrex.com/api/v1.1
    volumes:
      - .:/app
      - ruby2.3-bundle-cache:/usr/local/bundle
    working_dir: /app
    ports:
      - "5000:5000"
    command: rake watch
volumes:
  ruby2.3-bundle-cache:
    external: true
